### PR TITLE
Fix double profile modal

### LINKED ISSUE #1665: Double trigger on "Finish your profile" on the home page
https://coinbase.enterprise.slack.com/files/U068E3U6E4W/F085GPYMYH0/screenshare_-_2024-12-17_10_14_38_am.webm

### PR DESCRIPTION
**Pull request by eduardopicolo-cb**
closes #1665 

fixes 

## What changed? Why?

The UpateProfileForm shows twice due to two instances being mounted on the page (1 mobile & 1 desktop). The solution is to use javascript to conditionally mount the components.

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

### CODE REVIEW

File: src/components/app/pageUserProfile/index.tsx [hunk 1]
```diff
@@ -76,9 +81,12 @@ export function PageUserProfile({ params, user }: PageUserProfile) {
               </div>
             </div>
           </div>
-          <div className="hidden lg:flex">
-            <ProfileAndNFTButtons user={user} />
-          </div>
+
+          {!isMobile && (
+            <div className="hidden lg:flex">
```
Comment (twistershark) [inline src/components/app/pageUserProfile/index.tsx:86]: If we are adding this comparison, I think that we can remove the div as it was trying to do the same

File: src/components/app/pageUserProfile/index.tsx [hunk 2]
```diff
@@ -122,9 +130,11 @@ export function PageUserProfile({ params, user }: PageUserProfile) {
         </div>
       </section>
 
-      <div className="w-full lg:hidden">
-        <ProfileAndNFTButtons user={user} />
-      </div>
+      {isMobile && (
+        <div className="w-full lg:hidden">
```
Comment (twistershark) [inline src/components/app/pageUserProfile/index.tsx:134]: If we are adding this comparison, I think that we can remove the div as it was trying to do the same

**Review by twistershark — APPROVED** [review]

**Review by olavoparno — APPROVED** [review]
