### PR TITLE
Changes google places select results to be more strict in US

### LINKED ISSUE #947: Investigate user who has multiple submission errors
We should check mixpanel to investigate [this user](https://stand-with-crypto.sentry.io/issues/4830351975/?environment=production&project=4506490717470720&query=is%3Aunresolved+timesSeen%3A%3E%3D10&referrer=issue-stream&statsPeriod=30d&stream_index=0) and verify that the reason they submitted some many times and failed is because they were entering an invalid address, not because we have a bug in our address flow.

### PR DESCRIPTION
**Pull request by twistershark**
closes #947 

## What changed? Why?

This PR changes the google places api options based on the search results to prevent vague addresses to be used on email flow that would case Capitol Canary to fail when trying to find the related congressperson with the provided address.

## How has it been tested?

- [x] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

### CODE REVIEW

File: src/components/ui/googlePlacesSelect/index.tsx [hunk 1]
```diff
@@ -44,6 +50,22 @@ export const GooglePlacesSelect = React.forwardRef<
...
+  const usePlacesAutoCompleteResult = shouldLimitUSAddresses
+    ? data
+        ?.map(place =>
+          !place.description.includes('USA')
+            ? place
+            : !place.types.includes('route')
+              ? place
+              : null,
+        )
+        .filter(Boolean)
```
Comment (lucasrmp-cb) [inline src/components/ui/googlePlacesSelect/index.tsx:66]: Any reason not to do a single filter here?
```suggestion
    ? data?.filter(place => !place.description.includes('USA') || !place.types.includes('route'))
```

**Review by lucasrmp-cb — CHANGES_REQUESTED** [review]

File: src/components/ui/googlePlacesSelect/index.tsx (hunk 1 above)
Comment (twistershark) [reply src/components/ui/googlePlacesSelect/index.tsx]: Updated! Ty!

**Review by olavoparno — APPROVED** [review]

**Review by LucasRMP — APPROVED** [review]

**Review by lucasrmp-cb — APPROVED** [review]
