### PR TITLE
Fix signin button

### LINKED ISSUE #1681: Signin button stuck on wrong state

### PR DESCRIPTION
**Pull request by eduardopicolo-cb**
closes #1681 

fixes 

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

### CODE REVIEW

**Review by twistershark — APPROVED** [review]

File: src/components/app/navbar/navbarLoggedInButton/index.tsx [hunk 1]
```diff
@@ -57,7 +58,15 @@ export function NavbarLoggedInButton({ onOpenChange }: { onOpenChange: (open: bo
             <div className="max-w-[150px] truncate">{displayName}</div>
           </Button>
         ) : (
-          <Button data-testid="login-button">Sign In</Button>
+          <LoginDialogWrapper authenticatedContent={null}>
```
Comment (olavoparno) [inline src/components/app/navbar/navbarLoggedInButton/index.tsx:61]: if we're using this wrapper why not reduce the conditionals by adding displayName in `authenticatedContent`?

Comment (eduardopicolo-cb) [reply src/components/app/navbar/navbarLoggedInButton/index.tsx:61]: the wrapper is a escape hatch for that edge case, because the navbarLoggedInButton is already inside of an `authenticatedContent`.  This workaround is to allow an user to reconnect
