### PR TITLE
Fix: State events dialog showing past events

### LINKED ISSUE #1280: State events dialog is showing past events

### PR DESCRIPTION
**Pull request by twistershark**
closes #1280

## What changed? Why?

This PR fixes the state events dialog problem of showing past events. You can check the current error here: https://standwithcrypto.org/events/ga 

## How has it been tested?

- [x] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

### CODE REVIEW

File: src/components/app/pageEvents/components/eventsNearYou.tsx [hunk 1]
```diff
@@ -71,15 +70,7 @@ export function _EventsNearYou({ events }: EventsNearYouProps) {
...
-    return userState
-      ? events.filter(event => {
-          const eventDate = event.data?.time
-            ? new Date(`${event.data.date}T${event.data.time}`)
-            : new Date(event.data.date)
-
-          return event.data.state === userState && isAfter(eventDate, new Date())
-        })
-      : []
+    return userState ? events.filter(event => event.data.state === userState) : []
```
Comment (olavoparno) [inline src/components/app/pageEvents/components/eventsNearYou.tsx:73]: filter would already return an empty array if no match occurs with userState

Comment (twistershark) [reply src/components/app/pageEvents/components/eventsNearYou.tsx]: Updated!
