### PR TITLE
Fix hydration error on ntf-mint flow

### LINKED ISSUE #1654: Fix hydration error on homepage

### PR DESCRIPTION
**Pull request by eduardopicolo-cb**
closes #1654

fixes 

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

### CODE REVIEW

File: src/components/app/userActionFormNFTMint/sections/intro.tsx [hunk 1]
```diff
@@ -48,15 +47,16 @@ export function UserActionFormNFTMintIntro({
               loadingFallback={<FooterSkeleton />}
               useThirdwebSession={true}
             >
-              <Button data-testid="signin-button" size="lg">
-                Sign In
-              </Button>
+              <div className="flex w-full items-center justify-between gap-4">
```
Comment (olavoparno) [inline src/components/app/userActionFormNFTMint/sections/intro.tsx:50]: this whole block is clickable now, right? I don't see a big issue here but it's weird clicking on the text and opening the sign in dialog besides the very button

**Review by olavoparno — APPROVED** [review]

**Review by twistershark — APPROVED** [review]
