### PR TITLE
fix: ignore ZERO_RESULTS status for places api errors

### LINKED ISSUE #859: getGooglePlaceIdFromAddress no results with status ZERO_RESULTS
Sentry Issue: [PROD-SWC-WEB-1HQ](https://stand-with-crypto.sentry.io/issues/5051139135/?referrer=github_integration)

```
getGooglePlaceIdFromAddress no results with status ZERO_RESULTS
```

### PR DESCRIPTION
**Pull request by lucasrmp-cb**
closes #859 

fixes [PROD-SWC-WEB-1HQ](https://stand-with-crypto.sentry.io/issues/5051139135/?referrer=github_integration)

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

### CODE REVIEW

File: src/utils/server/getGooglePlaceIdFromAddress.ts [hunk 1]
```diff
@@ -19,19 +19,16 @@ export async function getGooglePlaceIdFromAddress(address: string) {
   )
   const data = (await response.json()) as {
     error_message?: string
+    info_messages?: string[]
     predictions: google.maps.places.AutocompletePrediction[]
-    status?: string
+    status: `${google.maps.places.PlacesServiceStatus}`
```
Comment (lucasrmp-cb) [inline src/utils/server/getGooglePlaceIdFromAddress.ts:24]: https://developers.google.com/maps/documentation/places/web-service/autocomplete#PlacesAutocompleteResponse

File: src/utils/server/getGooglePlaceIdFromAddress.ts [hunk 2]
```diff
@@ -19,19 +19,16 @@ export async function getGooglePlaceIdFromAddress(address: string) {
...
     return data.predictions[0].place_id
-  } else if (data.status) {
+  } else if (data.status !== 'ZERO_RESULTS') {
     Sentry.captureMessage(`getGooglePlaceIdFromAddress no results with status ${data.status}`, {
       extra: { address, data },
     })
-  } else {
-    Sentry.captureMessage('getGooglePlaceIdFromAddress no results', {
-      extra: { address, data },
-    })
```
Comment (lucasrmp-cb) [inline src/utils/server/getGooglePlaceIdFromAddress.ts:34]: Not necessary bc `status` is a required field

**Review by travisbloom-cb — APPROVED** [review]
