### PR TITLE
Fix: Leaderboard page build timeout

### LINKED ISSUE #1044: Improve leaderboard page build performance
For some reason, our build process in Vercel is breaking because the leaderboard static page generation is taking too long that is causing an timeout.

We need to investigate and fix this issue

### PR DESCRIPTION
**Pull request by twistershark**
closes #1044 

## What changed? Why?

This PR creates a new approach for returning default values for promises inside an Promise.all when a defined maximum timeout is reached. The idea here is to prevent the build page worker on Vercel from killing the build process because a promise was not resolved during the default 60 seconds limit on the Leaderboard page.

## How has it been tested?

- [x] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

### CODE REVIEW

File: src/data/web3/getENSDataFromCryptoAddress.ts [hunk 1]
```diff
@@ -14,27 +16,33 @@ async function _getENSDataMapFromCryptoAddresses(
...
     .filter(({ ensName }) => ensName)
-  const records = await Promise.all(
+
+  const records = await raceAll(
     addressesWithENS.map(address =>
       client.getEnsAvatar({
         name: address.ensName!,
       }),
     ),
+    SECONDS_DURATION['30_SECONDS'] * 1000,
```
Comment (travisbloom-cb) [inline src/data/web3/getENSDataFromCryptoAddress.ts:43]: isnt this way more than 30 seconds?

**Review by travisbloom-cb — APPROVED** [review]
