### PR TITLE
Fix profile form showing stale data after submit

### LINKED ISSUE #1142: Profile page info not updating

### PR DESCRIPTION
**Pull request by eduardopicolo-cb**
closes #1142 

## What changed? Why?

Fixes profile form displaying old data after submit and the profile visibility step is now only disabled on the onboarding flow

## How has it been tested?

- [x] Locally
- [x] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

### CODE REVIEW

File: src/hooks/useSections/index.tsx [hunk 1]
```diff
@@ -23,7 +24,7 @@ export function useSections<SectionKeys extends readonly string[]>({
 
   const goToSection: UseSectionsReturn<Key>['goToSection'] = React.useCallback(
     (section, options = {}) => {
```
Comment (LucasdRossi) [inline src/hooks/useSections/index.tsx:26]:
```suggestion
if (section === currentSection || skipSections?.includes(section)) {
```

**Review by LucasdRossi — APPROVED** [review]

**Review by LucasdRossi — APPROVED** [review]
