### PR TITLE
Fix async window open

### LINKED ISSUE #1869: Investigate /donate page errors

### PR DESCRIPTION
**Pull request by eduardopicolo-cb**
closes #1869

fixes 

## What changed? Why?

Safari blocks `window.open()` calls made without user interaction or in async functions. This PR fixes the problem by calling window.open synchronously on user click and then changes the url of that window.

[Same solution used for the Turbovote fix](https://github.com/Stand-With-Crypto/swc-web/pull/1396)

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

### CODE REVIEW

File: src/components/app/pageDonate/donateButton.tsx [hunk 1]
```diff
@@ -22,22 +24,23 @@ export function DonateButton() {
...
-            return commerceChargeResponse
-          },
-        ),
+      () => actionCreateCoinbaseCommerceCharge(),
     )
-    setButtonState('completed')
+
+    if (actionCreateCoinbaseCommerceChargeResponse.status !== 'success') {
+      return null
+    }
```
Comment (lucasrmp-cb) [inline src/components/app/pageDonate/donateButton.tsx:32]: Let's trigger a sentry error here

**Review by lucasrmp-cb — DISMISSED** [review]

**Review by olavoparno — APPROVED** [review]
