### PR TITLE
Prevents broken address from being processed on backfill repeatedly

### LINKED ISSUE #1234: Don't retry addresses that has error not related to api issues on usCongressionalDistrict backfill
Sentry Issue: [PROD-SWC-WEB-1HP](https://stand-with-crypto.sentry.io/issues/5051106861/?referrer=github_integration)

```
Error: 400 from GET https://www.googleapis.com/civicinfo/v2/representatives with json response
  File "swc-web/./src/utils/shared/fetchReq.ts", line 71, in c
    scope.setTransactionName(errorName)
  File "swc-web/./src/utils/shared/googleCivicInfo.ts", line 129, in result
    const CIVIC_BY_ADDRESS_ENDPOINT = 'https://www.googleapis.com/civicinfo/v2/representatives'
  File "swc-web/./src/utils/shared/getCongressionalDistrictFromAddress.ts", line 83, in maybeGetCongressionalDistrictFromAddress
    return { notFoundReason: 'USER_WITHOUT_ADDRESS' as const }
  File "swc-web/./src/inngest/functions/backfillCongressionalDistrictCronJob/index.ts", line 108, in backfillUsCongressionalDistricts
    domain: 'backfillUsCongressionalDistricts',
  File "swc-web/./src/inngest/functions/backfillCongressionalDistrictCronJob/index.ts", line 76, in _a
    `Finished backfilling batch ${i} of ${numBatches} maximum batches of addresses without usCongressionalDistrict`,
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by twistershark**
closes #1234 

## What changed? Why?

This PR saves the district number as 'NOT_FOUND' to prevent addresses that are broken from being processed everyday in the backfill cron job.

## How has it been tested?

- [x] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

### CODE REVIEW

**Review by lucasrmp-cb — DISMISSED** [review]

**Review by olavoparno — APPROVED** [review]

File: src/inngest/functions/backfillCongressionalDistrictCronJob/index.ts [hunk 1]
```diff
@@ -127,6 +127,34 @@ async function backfillUsCongressionalDistricts(
...
         })
       }
+      if (
+        ['NOT_USA_ADDRESS', 'NOT_SAME_STATE', 'NOT_SPECIFIC_ENOUGH'].includes(
+          usCongressionalDistrict.notFoundReason,
+        )
+      ) {
+        logger.info(
+          `No usCongressionalDistrict found for address ${address.id} because ${usCongressionalDistrict.notFoundReason}. Updating the usCongressionalDistrict to NOT_FOUND`,
+        )
```
Comment (mhamendes) [inline src/inngest/functions/backfillCongressionalDistrictCronJob/index.ts:137]: Those responses are not enough, they don't include error 400 on the API. Those errors will probably return as `CIVIC_API_DOWN`, so we must also treat those errors inside the query to the api.

**Review by mhamendes — CHANGES_REQUESTED** [review]

**Review by mhamendes — APPROVED** [review]
