### PR TITLE
Refresh place_id on error

### LINKED ISSUE #1652: Update place_id on failed google places calls
Google Places API sometimes fails with this error:

```
"The provided Place ID is no longer valid. Please refresh cached Place IDs as per https://developers.google.com/places/web-service/place-id#save-id"
```

We should check for it and update the place id we have in our database

[https://stand-with-crypto.sentry.io/issues/5041038508/?environment=production&project=4506[…]10&referrer=issue-stream&statsPeriod=30d&stream_index=5](https://stand-with-crypto.sentry.io/issues/5041038508/?environment=production&project=4506490717470720&query=is%3Aunresolved%20timesSeen%3A%3E%3D10&referrer=issue-stream&statsPeriod=30d&stream_index=5)

### PR DESCRIPTION
**Pull request by eduardopicolo-cb**
closes #1652

fixes 

## What changed? Why?

Calling getDetails with only place_id field will refresh the place_id and the request is free of charge. 

## How has it been tested?

- [ ] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

### CODE REVIEW

File: src/utils/web/googlePlaceUtils.ts [hunk 1]
```diff
@@ -41,16 +42,53 @@ const formatGooglePlacesResultToAddress = (
...
+        const result = await getAddressComponents(refreshedPlace.place_id)
+        return formatGooglePlacesResultToAddress({
+          ...result,
+          formattedDescription: prediction.description,
+          placeId: refreshedPlace.place_id,
+        })
+      } catch (refreshError) {
+        logger.error('Failed to refresh place_id:', refreshError)
+        throw refreshError
+      }
```
Comment (lucasrmp-cb) [inline src/utils/web/googlePlaceUtils.ts:79]: Let's abstract this into a new function for readability

**Review by olavoparno — APPROVED** [review]
