### PR TITLE
Pizza day - fixes pack

### LINKED ISSUE #852: Add go back functionality to pizza day activation flow
image

### PR DESCRIPTION
**Pull request by paulovictor-cb**
closes #852

fixes [bugs list](https://docs.google.com/document/d/19COMvwYeipJLLsiidKVDi6HNGMFwFQrwg2cxeZH00w0)

## What changed? Why?

- Deleted placeholder pizza page
- Changed DTSIPersonHeroCard to be non clickable as well
- Changed Tweet section title and subtitle sizes
- Fixed next button showing above the form component when the mobile height is not big enough
- Added a new type of address for google places api filter so that it works better in non US countries
- Added go back functionality to tweet section

## How has it been tested?

- [X] Locally
- [ ] Vercel Preview Branch
- [ ] Unit test
- [ ] Functional test

### CODE REVIEW

File: src/components/app/dtsiPersonHeroCard/index.tsx [hunk 1]
```diff
@@ -80,8 +81,11 @@ export function DTSIPersonHeroCard(props: Props) {
   const displayName = `${dtsiPersonFullName(person)}${politicalAbbrDisplayName}`
   return (
     <InternalLink
-      className="block shrink-0 overflow-hidden bg-white text-left shadow-md hover:!no-underline max-sm:rounded-3xl max-sm:border sm:inline-block sm:w-52 xl:w-72"
-      href={getIntlUrls(locale).politicianDetails(person.slug)}
+      className={cn(
+        'block shrink-0 overflow-hidden bg-white text-left shadow-md hover:!no-underline max-sm:rounded-3xl max-sm:border sm:inline-block sm:w-52 xl:w-72',
+        !isClickable && 'hover:cursor-default',
+      )}
+      href={isClickable ? getIntlUrls(locale).politicianDetails(person.slug) : ''}
```
Comment (travisbloom-cb) [inline src/components/app/dtsiPersonHeroCard/index.tsx:88]: you prob dont want it to be a link at all

File: src/components/app/pageBillDetails/index.tsx [hunk 2]
```diff
@@ -51,7 +51,7 @@ export function PageBillDetails(props: PageBillDetailsProps) {
         <p className="text-lg font-semibold">Analysis</p>
 
         <div className="space-y-6 text-center text-fontcolor-muted">
-          {analyses.length ? (
+          {analyses?.length ? (
```
Comment (travisbloom-cb) [inline src/components/app/pageBillDetails/index.tsx:54]: this shouldnt be needed

File: src/components/app/updateUserProfileForm/step1.tsx [hunk 3]
```diff
@@ -226,7 +226,11 @@ export function UpdateUserProfileForm({
               )}
             />
           )}
-          <Collapsible className="!my-4 max-md:!mt-auto" open={!!phoneNumberValue}>
+
+          <FormGeneralErrorMessage control={form.control} />
```
Comment (travisbloom-cb) [inline src/components/app/updateUserProfileForm/step1.tsx:230]: why?

Comment (paulovictor-cb) [reply src/components/app/updateUserProfileForm/step1.tsx:230]: This FormGeneralErrorMessage was here before. I moved the collapsible to be inside the same div as the next button because both needs to be at the bottom and it would be better to handle both together instead of replicating the same style logic for both.

File: src/components/app/pageBillDetails/index.tsx (hunk 2 above)
Comment (paulovictor-cb) [reply src/components/app/pageBillDetails/index.tsx:54]: Removed

Comment (paulovictor-cb) [reply src/components/app/pageBillDetails/index.tsx]: Changed it to be a div when isClickable is false

**Review by travisbloom-cb — APPROVED** [review]

**Review by travisbloom-cb — CHANGES_REQUESTED** [review]
we shouldnt pass this if its a href https://github.com/Stand-With-Crypto/swc-web/pull/890/commits/f6185c3f692a45b131f69e2b8b9259f968c1a231#diff-57834b4fedc3a7fd4aa1ea9c372ae99d165327aae5d8c5599fd5fe4d54e07466R91

**Review by travisbloom-cb — APPROVED** [review]
